-- AlterTable
ALTER TABLE `media_requests` ADD COLUMN `invalid_reply_count` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `last_invalid_reply_at` DATETIME(3) NULL,
    MODIFY `status` ENUM('PENDING', 'TEMPLATE_SENT', 'CONFIRMED', 'MEDIA_SENT', 'INVALID_RESPONSE_LIMIT', 'FAILED') NOT NULL DEFAULT 'PENDING';
