ALTER TABLE `media_requests`
  MODIFY `status` ENUM(
    'PENDING',
    'TEMPLATE_SENT',
    'RECONFIRMATION_SENT',
    'DECLINED',
    'CONFIRMED',
    'MEDIA_SENT',
    'INVALID_RESPONSE_LIMIT',
    'TEMPLATE_SEND_FAILED',
    'MEDIA_SEND_FAILED',
    'FAILED'
  ) NOT NULL DEFAULT 'PENDING';
