-- AlterTable
ALTER TABLE `media_requests` MODIFY `status` ENUM('PENDING', 'TEMPLATE_SENT', 'RECONFIRMATION_SENT', 'DECLINED', 'CONFIRMED', 'MEDIA_SENT', 'INVALID_RESPONSE_LIMIT', 'FAILED') NOT NULL DEFAULT 'PENDING';
